apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/dispatcher-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/polarbookshop/dispatcher-service
  newTag: 5fcaa8d5419c73f9b3a9ab5a6b9fbffc06ba5a5c

replicas:
- count: 1
  name: dispatcher-service
