apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/catalog-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/polarbookshop/catalog-service
  newTag: 1c369114ca13dca8d2d9606d183733530dd327e7

replicas:
- count: 2
  name: catalog-service
