apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/polarbookshop/order-service
  newTag: 7c909c224ce71a7c497fb2567c5f2b6dd9ee92df

replicas:
- count: 1
  name: order-service
