apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/edge-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/polarbookshop/edge-service
  newTag: 5ac728c427e5ecd410981804d87b0c8c1b24f8bc

replicas:
- count: 1
  name: edge-service
